### ISSUE TITLE
Q: Linux support?

### ISSUE THREAD

**Issue by techmagus** [killer415tv/gw2_speedometer#15]
Hi,

I am wondering, is there a guide on how to run this on Linux?

I'm stuck with this:
```shell
Traceback (most recent call last):
  File "/gw2/speedometer/speedometer_multilap.py", line 14, in <module>
    import pynput.keyboard._win32 
  File "/.local/lib/python3.10/site-packages/pynput/keyboard/_win32.py", line 37, in <module>
    from pynput._util.win32 import (
  File "/.local/lib/python3.10/site-packages/pynput/_util/win32.py", line 32, in <module>
    from ctypes import (
ImportError: cannot import name 'windll' from 'ctypes' (/usr/lib/python3.10/ctypes/__init__.py)

```

Thank you.

**Comment by morngrar** [comment]
It seems that there are some hard dependencies on the windows system libraries. I run linux as well, and would love to see this work. I have no idea how much work it would be --- or if it is even feasible --- however, without diving into the code.

**Comment by Brandieee** [comment]
Having looked into it some, here are a few pointers to get started:

- Direct imports of `pynput.keyboard._win32` which are not needed (unused and covered by generic pynput.keyboard imports)
- font loading hacks (can be solved by importing and using `pyglet`or foregoing custom fonts
- Reading of mumblelink memory mapped space
  - specifically, `tagname`is not supported on linux so determining which memory space to read has to be done in some other way, however that feels like it should be an already solved issue as well
